# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
    major: 1
    minor: 0
    patch: 0
name: $(major).$(minor).$(patch).$(Rev:r)
steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
- task: DotNetCoreCLI@2
  displayName: Pack
  inputs: 
    command: 'pack'
    outputDir: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: byPrereleaseNumber
    majorVersion: $(major)
    minorVersion: $(minor)
    patchVersion: $(patch)
- task: PublishBuildArtifacts@1
  displayName: Publish
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: Package