variables:
  ${{ if eq(length(split(variables['Build.SourceBranchName'], '.')), 2) }}:
    otxVersion: ${{ variables['Build.SourceBranchName'] }}
  ${{ else }}:
    otxVersion: '23.1'
name: $(otxVersion).$(Rev:r)
trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'byBuildNumber'
    buildProperties: 'Version=$(Build.BuildNumber)'
  displayName: Pack
- task: PublishBuildArtifacts@1
  displayName: Publish
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: Package